sqlite: &sqlite
  adapter: sqlite3
  database: 'db/development.sqlite3'
  timeout: 5000

production: &production
  adapter: postgresql
  encoding: unicode
  database: doers_production
  username: doers
  password: doers_password
  host: localhost
  pool: 5

development:
  <<: *sqlite

test:
  <<: *sqlite
  # /dev/shm means shared memory, fixes any :memory: option hacks
  database: '/dev/shm/doers-tests.sqlite3'
