postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  timeout: 5000
  pool: 5

production: &production
  <<: *postgresql
  database: doers

development:
  <<: *postgresql
  database: doers

test:
  <<: *postgresql
  database: doers_test
