sqlite: &sqlite
  adapter: sqlite3
  database: 'db/development.sqlite3'
  timeout: 5000

production: &production
  <<: *sqlite
  database: 'db/production.sqlit3'

development:
  <<: *sqlite

test:
  <<: *sqlite
  database: 'db/test.sqlite3'
