sqlite: &sqlite
  adapter: sqlite3
  database: 'db/development.sqlite3'
  timeout: 5000

production: &production
  <<: *sqlite
  database: 'db/production.sqlit3'

development:
  <<: *sqlite

test:
  <<: *sqlite
  # /dev/shm means shared memory, fixes any :memory: option hacks
  database: '/dev/shm/doers-tests.sqlite3'
