defaults: &defaults
  app_name: DOERS
  app_owner: Founden
  app_id: app.doersapp.com
  oauth2_providers:
    angel_list:
      client_id: 645e9a49faf15df3cf67853f1ad255bd
      secret_key: d7534214ae71a6ae79a0aa4ba5f7e4ff
  default_email: DOERS <no-reply@doersapp.com>
  contact_email: DOERS Team <support@doersapp.com>
  admin_regex: !ruby/regexp '/geekcelerator\.com/i'
  external_types:
    - angel_list
  notifications:
    asap: <%= 5.minutes %>
    offset: <%= 1.minutes %>
  aws:
    s3:
      protocol: 'https'
      bucket: 'assets.doersapp.com'
  mixpanel:
    token: 8c9917404d52607b8d3b265180f39721
  assets:
    image:
      sizes:
        thumb: 100x100#
        small: 300x300>
        medium: 600x600>
    cover:
      sizes:
        small: 280x280>
  promo_codes:
    - DOERS_VLAD
    - DOERS_STAS
    - DOERS_CATALINA
    - DOERS_ALEXANDRU
    - DOERS_STEFAN
    - DOERS_ANDREEA
  memcache:
    - mc4.dev.ec2.memcachier.com:11211
    -
      :username: 04f07b
      :password: 912903cba6
      :failover: true
      :socket_timeout: 1.5
      :socket_failure_delay: 0.2


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  github:
    oauth_token: 'a4aefdd92c8ff470da5a098bb5cbcedcc283fa15'
    owner: 'stas'
    repository: 'doers'
  oauth2_providers:
    angel_list:
      client_id: 1be58d394a63667825c2e5479fc9d617
      secret_key: fd70eb48c593ff0d5da95d144a38ee81
