defaults: &defaults
  app_name: <%= _('DOERS by Geekcelerator') %>
  app_id: doers.geekcelerator.com
  oauth_providers:
    twitter:
      client_id: vAODSxZcVZIoPH0wsBDP7A
      secret_key: AcBQmKP4JoSqHGt80Ut2tE5RlnITqsIwsWJNUgd8q8

development:
  <<: *defaults

test:
  <<: *defaults

production:
  github:
    oauth_token: 'a4aefdd92c8ff470da5a098bb5cbcedcc283fa15'
    owner: 'stas'
    repository: 'doers'
  <<: *defaults
