defaults: &defaults
  app_name: DOERS
  app_id: doersapp.com
  oauth2_providers:
    angel_list:
      client_id: 645e9a49faf15df3cf67853f1ad255bd
      secret_key: d7534214ae71a6ae79a0aa4ba5f7e4ff
  default_email: no-reply@doersapp.com
  contact_email: sos@doersapp.com
  admin_regex: !ruby/regexp '/geekcelerator\.com/i'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  github:
    oauth_token: 'a4aefdd92c8ff470da5a098bb5cbcedcc283fa15'
    owner: 'stas'
    repository: 'doers'
  oauth2_providers:
    angel_list:
      client_id: 1be58d394a63667825c2e5479fc9d617
      secret_key: fd70eb48c593ff0d5da95d144a38ee81
